-- Quotes table backing the public "Wall of Quotes" page. Admin-authored only
-- (no public submission form), managed from /admin/quotes with the service role key.
-- Run this once in the Supabase SQL Editor (or via `supabase db push` if the project is linked).

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  topic_key text not null check (topic_key in ('ikhlas', 'knowledge', 'patience', 'dunya', 'taqwa', 'brotherhood')),
  kind text not null default 'quote' check (kind in ('quote', 'passage')),
  title text,
  body text not null,
  author text not null,
  era text not null,
  published boolean not null default true
);

create index if not exists quotes_topic_key_idx on public.quotes (topic_key);
create index if not exists quotes_published_idx on public.quotes (published);

alter table public.quotes enable row level security;

-- Only published quotes are ever exposed to the anon/public key. Everything else
-- (drafts, edits, deletes) is admin-only via the service role key from /admin/quotes.
drop policy if exists "Allow public read of published quotes" on public.quotes;
create policy "Allow public read of published quotes"
  on public.quotes
  for select
  to anon
  using (published = true);

-- Seed the original 14 quotes so the Wall of Quotes keeps its existing content
-- after moving from the static lib/data/quotes.ts array to this table.
insert into public.quotes (id, topic_key, kind, title, body, author, era) values
  (1, 'ikhlas', 'quote', null, $q$Nothing has been harder for me to put right than my own intention — it turns over on me again and again.$q$, $q$Sufyān al-Thawrī$q$, 'd. 161 AH'),
  (2, 'knowledge', 'passage', $q$The Heart's True Nourishment$q$, $q$The heart carries a hunger that food and drink can never reach. It is fed only by knowledge of Allah, drawing near to Him, and turning to Him in sincerity. Give it anything else and it stays restless, however full the body becomes. A servant may fast from bread for a single day and break it at sunset — but a heart starved of remembrance can go a lifetime and never taste what it truly needs.$q$, $q$Ibn al-Qayyim al-Jawziyyah$q$, 'd. 751 AH'),
  (3, 'patience', 'quote', null, $q$We tasted the sweetness of life only once we had learned patience.$q$, $q$‘Umar ibn al-Khaṭṭāb$q$, 'd. 23 AH'),
  (4, 'dunya', 'quote', null, $q$Son of Adam, you are only a collection of days — each one that departs takes a portion of you with it.$q$, $q$Ḥasan al-Baṣrī$q$, 'd. 110 AH'),
  (5, 'dunya', 'passage', $q$A Shadow You Cannot Catch$q$, $q$The world behaves like a shadow: chase it, and it will always outpace you; turn your back on it instead, and it has no choice but to follow. Its comfort never arrives where you expect it, and its harm never departs when you assume it has. Do not build your certainty on something built on movement.$q$, $q$‘Alī ibn Abī Ṭālib$q$, 'd. 40 AH'),
  (6, 'taqwa', 'quote', null, $q$To abandon a deed because people are watching is showing off; to perform it for their sake is associating partners with Allah. Sincerity is when He frees you from both.$q$, $q$Fuḍayl ibn ‘Iyāḍ$q$, 'd. 187 AH'),
  (7, 'knowledge', 'quote', null, $q$Knowledge does not surrender itself to anyone who approaches it with arrogance; it opens only to those who come low before it.$q$, $q$Mālik ibn Anas$q$, 'd. 179 AH'),
  (8, 'patience', 'passage', $q$The Believer's Two Blessings$q$, $q$A believer's affairs are entirely good — a favour granted to no one else. If ease reaches him, he gives thanks, and that is good for him; if hardship befalls him, he endures patiently, and that too is good for him. Difficulty, looked at honestly, is only ever temporary — while the patience shown within it is recorded forever.$q$, $q$Ibn Taymiyyah$q$, 'd. 728 AH'),
  (9, 'brotherhood', 'quote', null, $q$Do not befriend anyone but a believer, and let none but the pious share your table.$q$, $q$‘Umar ibn al-Khaṭṭāb$q$, 'd. 23 AH'),
  (10, 'ikhlas', 'quote', null, $q$The soundness of the whole body follows the soundness of the heart — and the soundness of the heart follows how much of Allah alone it seeks.$q$, $q$Ibn al-Qayyim al-Jawziyyah$q$, 'd. 751 AH'),
  (11, 'dunya', 'quote', null, $q$You were not created for this world to remain in it, but only to cross it toward what comes after.$q$, $q$‘Umar ibn ‘Abd al-‘Azīz$q$, 'd. 101 AH'),
  (12, 'taqwa', 'passage', $q$A Definition Worth Memorising$q$, $q$Taqwā is not merely the avoidance of the obviously forbidden. It is placing a barrier between yourself and whatever draws you closer to sin — sometimes even things that are permitted, if they lead there. A servant reaches true taqwā only when he leaves what is harmless out of caution for what is harmful.$q$, $q$Ibn Rajab al-Ḥanbalī$q$, 'd. 795 AH'),
  (13, 'knowledge', 'quote', null, $q$Whoever does not taste the bitterness of learning even briefly will drink the humiliation of ignorance for the rest of his life.$q$, $q$Imām al-Shāfi‘ī$q$, 'd. 204 AH'),
  (14, 'brotherhood', 'quote', null, $q$A believer is a mirror for his brother: he removes his faults gently, exactly as he would want his own removed.$q$, $q$Ḥasan al-Baṣrī$q$, 'd. 110 AH')
on conflict (id) do nothing;

-- Explicit ids were used above so the seeded rows keep matching "No. 01"–"No. 14" on
-- the wall; bump the identity sequence so the next admin-created quote continues from 15.
select setval(pg_get_serial_sequence('public.quotes', 'id'), (select coalesce(max(id), 1) from public.quotes));
