-- Weekly class timetable, managed from /admin/schedule with the service role
-- key. One row per weekday (Mon–Fri) — matches the "one class a day" shape
-- of the admin dashboard design. Editing a row and clicking "Publish to
-- students" is what will make it visible to the (future) student portal.
-- Starts empty — classes are created from scratch via "+ Add class" in the
-- admin panel, not seeded here.
-- Run this once in the Supabase SQL Editor (or via `supabase db push` if the project is linked).

create table if not exists public.class_schedule (
  id bigint generated by default as identity primary key,
  day text not null check (day in ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')),
  subject text not null,
  start_time text not null,
  duration text not null,
  teacher text not null,
  color text not null default '#1182A3',
  status text not null default 'scheduled' check (status in ('scheduled', 'cancelled', 'rescheduled')),
  note text not null default '',
  sort_order int not null default 0,
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create unique index if not exists class_schedule_day_idx on public.class_schedule (day);

alter table public.class_schedule enable row level security;

-- The weekly timetable is meant to be visible to every enrolled student once
-- the student portal exists, so it's readable by the anon key. All writes
-- stay admin-only via the service role key from /admin/schedule.
drop policy if exists "Allow public read of class schedule" on public.class_schedule;
create policy "Allow public read of class schedule"
  on public.class_schedule
  for select
  to anon
  using (true);

create or replace function public.set_class_schedule_updated_at()
returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists class_schedule_set_updated_at on public.class_schedule;
create trigger class_schedule_set_updated_at
  before update on public.class_schedule
  for each row execute function public.set_class_schedule_updated_at();

-- No seed rows — the admin adds the real weekly timetable from
-- /admin/schedule ("+ Add class") once this migration has run.
