-- Enrolled students, their attendance records, and admin notes sent to them.
-- Powers /admin/students. Attendance rows are written by the student portal
-- (not built yet). No RLS read policy for anon is added yet since there's no
-- student-facing auth to scope rows to; add a `student_id = auth.uid()`-style
-- policy here once that portal exists.
-- Starts empty — students are enrolled from scratch via "+ Add student" in
-- the admin panel, not seeded here.
-- Run this once in the Supabase SQL Editor (or via `supabase db push` if the project is linked).

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  username text not null unique,
  level text not null,
  avatar_color text not null default '#1182A3'
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  class_date date not null,
  day text not null check (day in ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')),
  status text not null check (status in ('present', 'absent')),
  created_at timestamptz not null default now(),
  unique (student_id, class_date)
);

create index if not exists attendance_student_idx on public.attendance (student_id);
create index if not exists attendance_class_date_idx on public.attendance (class_date desc);

-- "Send a note to this student" from /admin/students writes here. Shown in
-- the student's notifications once the student portal can read its own rows.
create table if not exists public.student_notes (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read boolean not null default false
);

create index if not exists student_notes_student_idx on public.student_notes (student_id);

alter table public.students enable row level security;
alter table public.attendance enable row level security;
alter table public.student_notes enable row level security;
