-- Student portal login. Credentials are generated by the admin (Students ->
-- "Generate login") and shared with the student out of band (WhatsApp,
-- in person, etc.) — there is no student self-registration or password
-- reset flow. password_hash is null until an admin generates a login for
-- that student, so a student row can exist (for attendance tracking) before
-- they're able to sign in at all.
-- Run this once in the Supabase SQL Editor (or via `supabase db push` if the project is linked).

alter table public.students add column if not exists password_hash text;
alter table public.students add column if not exists last_login_at timestamptz;

-- Never expose password_hash through the anon/public key. Only the service
-- role (admin credential generation, student login route) reads or writes it.
alter table public.students enable row level security;
drop policy if exists "Deny anon access to students" on public.students;
create policy "Deny anon access to students"
  on public.students
  for all
  to anon
  using (false)
  with check (false);
-- test