-- Subject tasks, managed from /admin/tasks with the service role key and
-- shown on the student portal at /student/tasks. Tasks are global per
-- subject (like class_schedule), not assigned per-student — there is
-- deliberately no completion/progress column here; the portal only ever
-- shows what's assigned, never who has done it.
-- Run this once in the Supabase SQL Editor (or via `supabase db push` if the project is linked).

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  subject text not null,
  title text not null,
  description text not null default '',
  due_date date,
  attachment_url text,
  attachment_name text,
  attachment_path text
);

create index if not exists tasks_subject_idx on public.tasks (subject);
create index if not exists tasks_created_at_idx on public.tasks (created_at desc);

alter table public.tasks enable row level security;

-- Readable by every enrolled student, same as class_schedule. All writes
-- stay admin-only via the service role key from /admin/tasks.
drop policy if exists "Allow public read of tasks" on public.tasks;
create policy "Allow public read of tasks"
  on public.tasks
  for select
  to anon
  using (true);

-- Storage bucket for task attachments (worksheets, PDFs, etc). Uploaded
-- and deleted only from /api/admin/tasks via the service role key, which
-- bypasses storage RLS entirely — the public policy below only covers reads.
insert into storage.buckets (id, name, public)
values ('task-attachments', 'task-attachments', true)
on conflict (id) do nothing;

drop policy if exists "Public read of task attachments" on storage.objects;
create policy "Public read of task attachments"
  on storage.objects
  for select
  to public
  using (bucket_id = 'task-attachments');

-- No seed rows — tasks are created from scratch via "+ Add task" in the
-- admin panel once this migration has run.
